/** Human one-line summaries keyed by `${method} ${path}`. */
export const OPERATION_SUMMARIES: Record<string, string> = {
  "POST /v2/uploads":
    "Create a single-request streaming upload session for an attachment of the declared size.",
  "PUT /v2/uploads/:id/bytes":
    "Stream the complete declared byte body in ONE request. The store is single-shot: a short, oversized, or interrupted PUT cancels the upload and discards partial bytes — retry by creating a new upload and resending from byte zero. Not resumable.",
  "GET /v2/uploads/:id":
    "Read an upload session's status and received byte count (diagnostic on a cancelled upload, not a resumable offset).",
  "DELETE /v2/uploads/:id": "Abort and discard an in-progress upload session.",
  "POST /v2/uploads/:id/finalize": "Finalize an upload into a durable attachment resource.",
  "POST /v2/handshake": "Negotiate the control protocol major before product calls.",
  "GET /v2/daemon/status":
    "Read daemon activity, capacity, current/admission memory and event-loop window facts.",
  "GET /v2/operations": "List the implemented operations (this catalog).",
  "POST /v2/maintenance/gc": "Run retention GC over expired run trees and expired trash threads.",
  "GET /v2/agent-capabilities": "List the agent capability catalog this engine advertises.",
  "GET /v2/run-applicability":
    "Project the root-scoped Git prerequisite for every run/workspace shape.",
  "GET /v2/global/events": "Subscribe to the global cross-project event stream (SSE).",
  "GET /v2/quota": "Read cached per-profile harness quota snapshots.",
  "POST /v2/quota": "Refresh and read per-profile harness quota snapshots.",
  "GET /v2/account-pools":
    "Read the per-harness account-pool routing verdict (who an unpinned run routes to next) under the unified account model.",
  "GET /v2/credential-profiles": "List credential profiles per harness.",
  "POST /v2/credential-profiles": "Create a credential profile for a harness.",
  "PATCH /v2/credential-profiles/:harness/:profileId":
    "Toggle a credential profile's enabled state (the accounts Enabled row).",
  "DELETE /v2/credential-profiles/:harness/:profileId": "Delete a harness credential profile.",
  "POST /v2/accounts-migration/rollback":
    "Reverse the unified-accounts startup migration (the supported downgrade path): continuity keys return to the engine default and the auto-registered row leaves the registry.",
  "GET /v2/harnesses": "List installed harnesses and their availability.",
  "GET /v2/projects": "List registered projects (durable handles).",
  "POST /v2/projects": "Register a project root as a durable handle.",
  "POST /v2/projects/:id/relink": "Relink a registered project to a new root.",
  "DELETE /v2/projects/:id":
    "Remove a registered project: retire the registry entry and archive its journal partition. Refused (409) while any non-purged thread or live/queued run references it; run artifacts are left to normal GC.",
  "GET /v2/projects/:id/events": "Subscribe to a project's event stream (SSE).",
  "GET /v2/projects/:id/outputs": "List a project's durable outputs (artifacts/).",
  "GET /v2/projects/:id/outputs/<path>": "Fetch one durable output file from a project.",
  "GET /v2/harnesses/:id/models": "List a harness's selectable models.",
  "POST /v2/harnesses/:id/auth-readiness": "Re-check a harness's auth readiness (dry).",
  "GET /v2/runs":
    "List a bounded, newest-first, keyset-paginated page of durable run summaries visible to the daemon.",
  "POST /v2/runs": "Start a run and return its durable handle.",
  "GET /v2/runs/:id": "Read a run's full detail snapshot.",
  "POST /v2/runs/:id/retry": "Retry a run, returning a new durable handle.",
  "GET /v2/runs/:id/run-again": "Draft a run-again request from a prior run.",
  "POST /v2/runs/:id/apply":
    "Apply a run's work product to the live tree; replay of an already-delivered run is a typed idempotent no-op.",
  "POST /v2/runs/:id/apply/check":
    "Dry-check whether a run's patch would apply; an already-delivered run reports the safe already-applied no-op.",
  "GET /v2/runs/:id/artifacts": "List a run tree's technical artifacts.",
  "GET /v2/runs/:id/artifacts/<path>": "Fetch one artifact file from a run tree.",
  "POST /v2/runs/:id/control": "Cancel a queued or running run.",
  "POST /v2/runs/:id/decision": "Record an operator unblock/rerun decision on a run.",
  "GET /v2/runs/:id/events": "Replay + tail a run's event stream (SSE).",
  "POST /v2/runs/:id/interactions/:id/answer": "Answer a run's pending interactive question.",
  "POST /v2/runs/:id/messages":
    "Place a live message into a run's active attempt and return a typed receipt: delivered (native consumption observed), accepted (native acceptance observed, consumption unproved), rejected, not_active, unsupported, or delivery_unknown. Every typed outcome answers HTTP 200 (unlike the answer and control routes); the Idempotency-Key is the message id and a replay returns the stored receipt.",
  "GET /v2/runs/:id/produced": "List a run's produced project outputs.",
  "GET /v2/runs/:id/produced/<path>": "Fetch one produced project-output file from a run.",
  "GET /v2/threads": "List conversation threads.",
  "POST /v2/threads": "Create a conversation thread.",
  "GET /v2/threads/:id": "Read a thread's detail (turns + head).",
  "PATCH /v2/threads/:id": "Update a thread's sticky settings (harness/profile/access).",
  "POST /v2/threads/:id/trash": "Move a thread to trash.",
  "POST /v2/threads/:id/restore": "Restore a thread from trash.",
  "POST /v2/threads/:id/purge": "Permanently purge a trashed thread.",
  "POST /v2/threads/:id/apply": "Apply the thread's latest run work product.",
  "POST /v2/threads/:id/turns": "Enqueue a new turn on a thread.",
  "POST /v2/threads/:id/turns/:id/retry": "Retry a thread turn.",
  "GET /v2/trust": "List protected-path trust state.",
  "POST /v2/trust": "Update protected-path trust state.",
  "GET /v2/settings": "Read the settings snapshot.",
  "POST /v2/settings": "Update settings.",
  "GET /v2/secrets": "List stored secret handles (values never returned).",
  "POST /v2/secrets": "Set a stored secret value.",
  "DELETE /v2/secrets/:id": "Delete a stored secret.",
  "GET /v2/setup/jobs": "List harness setup/login jobs.",
  "POST /v2/setup/jobs": "Start a harness setup/login job.",
  "GET /v2/setup/jobs/:id": "Read a setup job's status.",
  "GET /v2/setup/jobs/:id/snapshot": "Read a setup job's terminal snapshot.",
  "GET /v2/setup/jobs/:id/events": "Tail a setup job's event stream (SSE).",
  "POST /v2/setup/jobs/:id/cancel": "Cancel a setup job.",
  "POST /v2/setup/jobs/:id/input":
    "Deliver the user's one-time sign-in input (e.g. a pasted OAuth code) to a waiting login job; the value is transient and never journaled.",
  "POST /v2/setup/jobs/:id/reconcile": "Reconcile a setup job's state.",
  "POST /v2/setup/jobs/:id/extend": "Extend a setup job's deadline.",
  "GET /v2/recovery/partitions/:id": "Inspect a journal partition for recovery.",
  "POST /v2/recovery/partitions/:id/validate": "Validate a journal partition (dry).",
  "POST /v2/recovery/partitions/:id/export": "Export a journal partition (dry).",
  "POST /v2/recovery/partitions/:id/quarantine": "Quarantine a corrupt journal partition.",
};
