// GENERATED by scripts/gen-version.mjs from the root package.json — do not edit by hand.
// Run `pnpm gen:version` after bumping the root version (changesets keeps the
// workspace manifests in lockstep). The docs-truth gate enforces parity.
export const CLAUDEXOR_VERSION = "3.1.0";
