#!/usr/bin/env node
/**
 * Single-producer version SSOT. Reads the ONE source of truth — the root
 * package.json `version` — and writes the generated `CLAUDEXOR_VERSION`
 * constant that the CLI banner / --version, plugin shims, MCP/ACP servers, and
 * adapter manifests all import. Changesets keeps the workspace manifests in
 * lockstep (`fixed`); the docs-truth gate (scripts/docs-truth-check.mjs)
 * enforces constant == root == every manifest so the version can never drift.
 *
 *   node scripts/gen-version.mjs   # regenerate after bumping the root version
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const rootPkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = rootPkg.version;
if (typeof version !== "string" || version.trim() === "") {
  throw new Error("root package.json has no version string");
}

const out = join(root, "packages", "util", "src", "version.ts");
const body = `// GENERATED by scripts/gen-version.mjs from the root package.json — do not edit by hand.
// Run \`pnpm gen:version\` after bumping the root version (changesets keeps the
// workspace manifests in lockstep). The docs-truth gate enforces parity.
export const CLAUDEXOR_VERSION = ${JSON.stringify(version)};
`;
writeFileSync(out, body);
process.stdout.write(`Wrote CLAUDEXOR_VERSION="${version}" to ${out}\n`);
