/**
 * Generates JSON Schema files from the Zod SSOT into packages/schema/generated/.
 * Run via `pnpm schema:gen`. CI verifies the output is committed and up to date.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { zodToJsonSchema } from "zod-to-json-schema";
import {
  BudgetLease,
  PaidBudget,
  BudgetObservation,
  ControlApplyCheckRequest,
  ControlApplyRequest,
  ControlAuthReadinessRefreshRequest,
  ControlAuthReadinessRefreshResponse,
  ControlHarnessListResponse,
  ControlHarnessModelsResponse,
  ControlInteractionAnswerRequest,
  ControlInteractionAnswerResponse,
  ControlPendingInteraction,
  ControlQuotaResponse,
  ControlCredentialProfilesResponse,
  ControlCredentialProfileCreateRequest,
  ControlCredentialProfileCreateResponse,
  ControlCredentialProfileUpdateRequest,
  ControlCredentialProfileUpdateResponse,
  ControlCredentialProfileDeleteResponse,
  CredentialProfile,
  CredentialProfileStatus,
  ControlQueuedRunInfo,
  ControlRunDetail,
  ControlRunStartInfo,
  ControlRunStartResponse,
  ControlRunStartRequest,
  ControlUploadCreateRequest,
  ControlUploadStatus,
  ControlUploadFinalizeRequest,
  ControlResource,
  ControlThreadTurnRequest,
  ControlRunRetryResponse,
  ControlRunAgainDraft,
  ControlRunSummary,
  ControlRunListResponse,
  ControlRunControlRequest,
  ControlRunControlResponse,
  ControlGcReceipt,
  ControlGcRequest,
  ControlSecretListResponse,
  ControlSecretMutationResponse,
  ControlSecretSetRequest,
  ControlSetupJob,
  ControlSetupJobCreateRequest,
  ControlSetupJobEvent,
  ControlSetupJobSnapshot,
  ControlSetupJobListFilter,
  ControlSetupJobListResponse,
  ControlSettingsSnapshot,
  ControlHarnessSettingsPatch,
  ControlSettingsUpdateRequest,
  ConformanceReport,
  ContextPack,
  DecisionRecord,
  GateResult,
  GlobalConfig,
  HarnessEvent,
  HarnessManifest,
  HarnessModel,
  HarnessStatusDto,
  ProjectConfig,
  RawContextPacket,
  RawGitPatchEnvelope,
  ReviewFinding,
  RouteFallbackPayload,
  RoutePrimaryDivergedPayload,
  RouteProof,
  RunEvent,
  RunFailure,
  RunControl,
  RunTelemetry,
  Session,
  ContinuityDisclosure,
  LaneCheckpoint,
  TaskContract,
  TestCommandInvocation,
  Thread,
  ThreadTurn,
  TrustConfig,
  WorkProduct,
  WorkspaceEnvelope,
  SecretMetadata,
  ControlRunDecisionRequest,
  ControlRunDecisionResponse,
  ControlThread,
  ControlThreadCreateRequest,
  ControlThreadUpdateRequest,
  ControlThreadApplyRequest,
  ControlThreadApplyResponse,
  ControlThreadDetail,
  ControlThreadTurnResponse,
  ControlThreadListResponse,
  ControlTrustListResponse,
  AgentCapabilityCatalog,
  ApplyEligibility,
  McpRunToolResult,
  McpRunHandleResult,
  ControlTrustState,
  ControlTrustUpdateRequest,
  ControlProblem,
  ControlHandshakeRequest,
  ControlHandshakeResponse,
  ControlOperationDescriptor,
  ControlOperationCatalog,
  ControlArtifactListResponse,
  ControlProjectOutputsResponse,
  ControlApplyCheckResponse,
  ControlDeliveryResponse,
  ControlJournalInspection,
  ControlJournalValidation,
  ControlJournalExportReceipt,
  ControlJournalQuarantineRequest,
  ControlJournalQuarantineReceipt,
  ControlJournalEvent,
  ThreadHeadPing,
  Project,
  ControlProject,
  ControlProjectListResponse,
  ControlProjectRegisterRequest,
  ControlProjectRelinkRequest,
} from "../src/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "generated");
mkdirSync(outDir, { recursive: true });
for (const name of readdirSync(outDir)) {
  if (name.endsWith(".schema.json")) rmSync(join(outDir, name));
}

const schemas = {
  TaskContract,
  TestCommandInvocation,
  ContextPack,
  RawContextPacket,
  RawGitPatchEnvelope,
  HarnessManifest,
  ConformanceReport,
  ReviewFinding,
  WorkProduct,
  BudgetLease,
  PaidBudget,
  BudgetObservation,
  RouteProof,
  DecisionRecord,
  GateResult,
  RunEvent,
  RunTelemetry,
  HarnessEvent,
  ProjectConfig,
  GlobalConfig,
  TrustConfig,
  WorkspaceEnvelope,
  ControlRunStartRequest,
  ControlUploadCreateRequest,
  ControlUploadStatus,
  ControlUploadFinalizeRequest,
  ControlResource,
  ControlThreadTurnRequest,
  ControlRunStartInfo,
  ControlRunStartResponse,
  ControlRunRetryResponse,
  ControlRunAgainDraft,
  ControlQueuedRunInfo,
  ControlRunSummary,
  ControlRunListResponse,
  ControlRunDetail,
  RunFailure,
  RunControl,
  ControlRunControlRequest,
  ControlRunControlResponse,
  ControlApplyCheckRequest,
  ControlApplyRequest,
  ControlAuthReadinessRefreshRequest,
  ControlAuthReadinessRefreshResponse,
  ControlSetupJob,
  ControlSetupJobCreateRequest,
  ControlSetupJobEvent,
  ControlSetupJobSnapshot,
  ControlSetupJobListFilter,
  ControlSetupJobListResponse,
  HarnessStatusDto,
  HarnessModel,
  ControlHarnessListResponse,
  ControlHarnessModelsResponse,
  ControlSettingsSnapshot,
  ControlHarnessSettingsPatch,
  ControlSettingsUpdateRequest,
  ControlPendingInteraction,
  ControlQuotaResponse,
  ControlCredentialProfilesResponse,
  ControlCredentialProfileCreateRequest,
  ControlCredentialProfileCreateResponse,
  ControlCredentialProfileUpdateRequest,
  ControlCredentialProfileUpdateResponse,
  ControlCredentialProfileDeleteResponse,
  CredentialProfile,
  CredentialProfileStatus,
  ControlInteractionAnswerRequest,
  ControlInteractionAnswerResponse,
  SecretMetadata,
  ControlGcReceipt,
  ControlGcRequest,
  ControlSecretListResponse,
  ControlSecretMutationResponse,
  ControlSecretSetRequest,
  Thread,
  Session,
  ThreadTurn,
  ContinuityDisclosure,
  LaneCheckpoint,
  RouteFallbackPayload,
  RoutePrimaryDivergedPayload,
  ControlRunDecisionRequest,
  ControlRunDecisionResponse,
  ControlThread,
  ControlThreadCreateRequest,
  ControlThreadUpdateRequest,
  ControlThreadApplyRequest,
  ControlThreadApplyResponse,
  ControlThreadListResponse,
  ControlThreadDetail,
  ControlThreadTurnResponse,
  ControlTrustListResponse,
  AgentCapabilityCatalog,
  ApplyEligibility,
  McpRunToolResult,
  McpRunHandleResult,
  ControlTrustState,
  ControlTrustUpdateRequest,
  ControlProblem,
  ControlHandshakeRequest,
  ControlHandshakeResponse,
  ControlOperationDescriptor,
  ControlOperationCatalog,
  ControlArtifactListResponse,
  ControlProjectOutputsResponse,
  ControlApplyCheckResponse,
  ControlDeliveryResponse,
  ControlJournalInspection,
  ControlJournalValidation,
  ControlJournalExportReceipt,
  ControlJournalQuarantineRequest,
  ControlJournalQuarantineReceipt,
  ControlJournalEvent,
  ThreadHeadPing,
  Project,
  ControlProject,
  ControlProjectListResponse,
  ControlProjectRegisterRequest,
  ControlProjectRelinkRequest,
} as const;

for (const [name, schema] of Object.entries(schemas)) {
  // Draft-07 is the newest dialect zod-to-json-schema 3.x actually supports;
  // the previously requested "jsonSchema2020-12" was silently ignored and
  // produced an invalid draft-4/7 hybrid (boolean exclusiveMinimum).
  // CI compiles every generated file with ajv (validate-generated-schemas.mjs).
  const json = zodToJsonSchema(schema, { name, target: "jsonSchema7" }) as Record<string, unknown>;
  json.$schema = "http://json-schema.org/draft-07/schema#";
  writeFileSync(join(outDir, `${name}.schema.json`), JSON.stringify(json, null, 2) + "\n");
}

console.log(`Wrote ${Object.keys(schemas).length} JSON schemas to ${outDir}`);
