/**
 * Generates JSON Schema files from the Zod SSOT into packages/schema/generated/.
 * Run via `pnpm schema:gen`. CI verifies the output is committed and up to date.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { zodToJsonSchema } from "zod-to-json-schema";
import {
  EffortResolution,
  ProcessingPreference,
  ProcessingCapability,
  ProcessingReceipt,
  ProcessingCostBasis,
  UsageCostBasis,
  UsageCostSummary,
  AttemptExecutionEvidence,
  WorkspaceKind,
  WorkspaceFilesManifest,
  ControlModelSourcesAccountsResponse,
  ControlModelSourcesQueryResponse,
  ControlModelAccountCatalogResponse,
  ControlModelCatalogQueryResponse,
  ControlHarnessAccountCatalog,
  ControlHarnessAccountModelsResponse,
  ControlHarnessModelsQueryResponse,
  BudgetLease,
  PaidBudget,
  BudgetObservation,
  ControlApplyCheckRequest,
  ControlApplyRequest,
  ControlAuthReadinessRefreshRequest,
  ControlAuthReadinessRefreshResponse,
  ControlHarnessListResponse,
  ControlHarnessModelsResponse,
  ControlInteractionAnswerRequest,
  ControlInteractionAnswerResponse,
  ControlRunMessageRequest,
  ControlRunMessageResponse,
  ControlPendingInteraction,
  ControlQuotaRefreshRequest,
  ControlQuotaResponse,
  ControlCredentialProfilesResponse,
  ControlCredentialProfilesSnapshotResponse,
  ControlCredentialProfilesQueryResponse,
  ControlCredentialProfileCreateRequest,
  ControlCredentialProfileCreateResponse,
  ControlCredentialProfileUpdateRequest,
  ControlCredentialProfileUpdateResponse,
  ControlCredentialProfileDeleteResponse,
  ControlAccountPoolsResponse,
  ControlHarnessAccountPool,
  ControlPoolNextUp,
  ControlAccountsMigrationRollbackRequest,
  ControlAccountsMigrationRollbackResponse,
  AccountsUnifiedMigrationFile,
  CredentialProfile,
  CredentialProfileStatus,
  ControlQueuedRunInfo,
  ControlRunDetail,
  ControlRunStartInfo,
  ControlRunStartResponse,
  ControlRunStartRequest,
  ControlUploadCreateRequest,
  ModelCallRequest,
  ModelCallResult,
  ControlModelCatalogResponse,
  ControlModelSourcesResponse,
  ControlModelOperationCreateRequest,
  ControlModelOperationDetail,
  ControlModelOperationAckRequest,
  ControlModelOperationControlRequest,
  ControlImageOperationCreateRequest,
  ControlImageOperationDetail,
  ControlImageOperationAckRequest,
  ControlImageOperationControlRequest,
  ImageCallRequest,
  ImageCallResult,
  ControlUploadStatus,
  ControlUploadFinalizeRequest,
  ControlResource,
  ControlThreadTurnRequest,
  ControlRunRetryResponse,
  ControlRunAgainDraft,
  ControlRunSummary,
  ControlRunListResponse,
  ControlDaemonStatus,
  CommandListQuery,
  RunListQuery,
  ControlRunControlRequest,
  ControlRunControlResponse,
  ControlGcReceipt,
  ControlGcRequest,
  ControlSecretListResponse,
  ControlSecretMutationResponse,
  ControlSecretSetRequest,
  ControlSetupJob,
  ControlSetupJobCreateRequest,
  ControlSetupJobInputRequest,
  ControlSetupJobEvent,
  ControlSetupJobSnapshot,
  ControlSetupJobListFilter,
  ControlSetupJobListResponse,
  ControlSettingsSnapshot,
  ControlHarnessSettingsPatch,
  ControlSettingsUpdateRequest,
  ConformanceReport,
  ContextPack,
  DecisionRecord,
  GateResult,
  GlobalConfig,
  HarnessEvent,
  HarnessManifest,
  HarnessModel,
  HarnessStatusDto,
  ProjectConfig,
  RawContextPacket,
  RawGitPatchEnvelope,
  ReviewFinding,
  RouteFallbackPayload,
  OutputReadyPayload,
  RoutePrimaryDivergedPayload,
  RoutePoolDegradedPayload,
  RouteProof,
  RunEvent,
  RunFailure,
  RunControl,
  StructuredOutputConformance,
  RunTelemetry,
  RunFacts,
  Session,
  SessionCapsule,
  RunResumable,
  RunContinuityReceipt,
  ContinuityDisclosure,
  LaneCheckpoint,
  TaskContract,
  TestCommandInvocation,
  Thread,
  ThreadTurn,
  TrustConfig,
  WorkProduct,
  WorkspaceEnvelope,
  EnvelopeCustody,
  ControlRetainedEnvelope,
  SecretMetadata,
  ControlRunDecisionRequest,
  ControlRunDecisionResponse,
  ControlThread,
  ControlThreadCreateRequest,
  ControlThreadUpdateRequest,
  ControlThreadApplyRequest,
  ControlThreadApplyResponse,
  ControlThreadDetail,
  ControlThreadTurnResponse,
  ControlThreadListResponse,
  ControlTrustListResponse,
  AgentCapabilityCatalog,
  ApplyEligibility,
  McpRunToolResult,
  McpRunHandleResult,
  McpThreadTurnResult,
  ControlTrustState,
  ControlTrustUpdateRequest,
  ControlProblem,
  ControlHandshakeRequest,
  ControlHandshakeResponse,
  ControlOperationParameter,
  ControlOperationDescriptor,
  ControlOperationCatalog,
  ControlArtifactListResponse,
  ControlProjectOutputsResponse,
  ControlApplyCheckResponse,
  ControlDeliveryResponse,
  ControlJournalInspection,
  ControlJournalValidation,
  ControlJournalExportReceipt,
  ControlJournalQuarantineRequest,
  ControlJournalQuarantineReceipt,
  ControlJournalEvent,
  ThreadHeadPing,
  JournaledRunCreatedPayload,
  Project,
  ControlProject,
  ControlProjectListResponse,
  ControlProjectRegisterRequest,
  ControlProjectRelinkRequest,
  ControlProjectRemoveReceipt,
  ControlDirectoryEntry,
  ControlDirectoryListing,
  GitCapability,
  ControlRunApplicabilityResponse,
} from "../src/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "generated");
mkdirSync(outDir, { recursive: true });
for (const name of readdirSync(outDir)) {
  if (name.endsWith(".schema.json")) rmSync(join(outDir, name));
}

const schemas = {
  EffortResolution,
  ProcessingPreference,
  ProcessingCapability,
  ProcessingReceipt,
  ProcessingCostBasis,
  UsageCostBasis,
  UsageCostSummary,
  AttemptExecutionEvidence,
  WorkspaceKind,
  WorkspaceFilesManifest,
  ControlModelSourcesAccountsResponse,
  ControlModelSourcesQueryResponse,
  ControlModelAccountCatalogResponse,
  ControlModelCatalogQueryResponse,
  ControlHarnessAccountCatalog,
  ControlHarnessAccountModelsResponse,
  ControlHarnessModelsQueryResponse,
  ModelCallRequest,
  ModelCallResult,
  ControlModelCatalogResponse,
  ControlModelSourcesResponse,
  ControlModelOperationCreateRequest,
  ControlModelOperationDetail,
  ControlModelOperationAckRequest,
  ControlModelOperationControlRequest,
  ImageCallRequest,
  ImageCallResult,
  ControlImageOperationCreateRequest,
  ControlImageOperationDetail,
  ControlImageOperationAckRequest,
  ControlImageOperationControlRequest,
  TaskContract,
  TestCommandInvocation,
  ContextPack,
  RawContextPacket,
  RawGitPatchEnvelope,
  HarnessManifest,
  ConformanceReport,
  ReviewFinding,
  WorkProduct,
  BudgetLease,
  PaidBudget,
  BudgetObservation,
  RouteProof,
  DecisionRecord,
  GateResult,
  RunEvent,
  StructuredOutputConformance,
  RunTelemetry,
  RunFacts,
  HarnessEvent,
  ProjectConfig,
  GlobalConfig,
  TrustConfig,
  WorkspaceEnvelope,
  EnvelopeCustody,
  ControlRetainedEnvelope,
  ControlRunStartRequest,
  ControlUploadCreateRequest,
  ControlUploadStatus,
  ControlUploadFinalizeRequest,
  ControlResource,
  ControlThreadTurnRequest,
  ControlRunStartInfo,
  ControlRunStartResponse,
  ControlRunRetryResponse,
  ControlRunAgainDraft,
  ControlQueuedRunInfo,
  ControlRunSummary,
  ControlRunListResponse,
  ControlDaemonStatus,
  CommandListQuery,
  RunListQuery,
  ControlRunDetail,
  RunFailure,
  RunControl,
  ControlRunControlRequest,
  ControlRunControlResponse,
  ControlApplyCheckRequest,
  ControlApplyRequest,
  ControlAuthReadinessRefreshRequest,
  ControlAuthReadinessRefreshResponse,
  ControlSetupJob,
  ControlSetupJobCreateRequest,
  ControlSetupJobInputRequest,
  ControlSetupJobEvent,
  ControlSetupJobSnapshot,
  ControlSetupJobListFilter,
  ControlSetupJobListResponse,
  HarnessStatusDto,
  HarnessModel,
  ControlHarnessListResponse,
  ControlHarnessModelsResponse,
  ControlSettingsSnapshot,
  ControlHarnessSettingsPatch,
  ControlSettingsUpdateRequest,
  ControlPendingInteraction,
  ControlQuotaRefreshRequest,
  ControlQuotaResponse,
  ControlCredentialProfilesResponse,
  ControlCredentialProfilesSnapshotResponse,
  ControlCredentialProfilesQueryResponse,
  ControlCredentialProfileCreateRequest,
  ControlCredentialProfileCreateResponse,
  ControlCredentialProfileUpdateRequest,
  ControlCredentialProfileUpdateResponse,
  ControlCredentialProfileDeleteResponse,
  ControlAccountPoolsResponse,
  ControlHarnessAccountPool,
  ControlPoolNextUp,
  ControlAccountsMigrationRollbackRequest,
  ControlAccountsMigrationRollbackResponse,
  AccountsUnifiedMigrationFile,
  CredentialProfile,
  CredentialProfileStatus,
  GitCapability,
  ControlRunApplicabilityResponse,
  ControlInteractionAnswerRequest,
  ControlInteractionAnswerResponse,
  ControlRunMessageRequest,
  ControlRunMessageResponse,
  SecretMetadata,
  ControlGcReceipt,
  ControlGcRequest,
  ControlSecretListResponse,
  ControlSecretMutationResponse,
  ControlSecretSetRequest,
  Thread,
  Session,
  SessionCapsule,
  RunResumable,
  RunContinuityReceipt,
  ThreadTurn,
  ContinuityDisclosure,
  LaneCheckpoint,
  RouteFallbackPayload,
  OutputReadyPayload,
  RoutePrimaryDivergedPayload,
  RoutePoolDegradedPayload,
  ControlRunDecisionRequest,
  ControlRunDecisionResponse,
  ControlThread,
  ControlThreadCreateRequest,
  ControlThreadUpdateRequest,
  ControlThreadApplyRequest,
  ControlThreadApplyResponse,
  ControlThreadListResponse,
  ControlThreadDetail,
  ControlThreadTurnResponse,
  ControlTrustListResponse,
  AgentCapabilityCatalog,
  ApplyEligibility,
  McpRunToolResult,
  McpRunHandleResult,
  McpThreadTurnResult,
  ControlTrustState,
  ControlTrustUpdateRequest,
  ControlProblem,
  ControlHandshakeRequest,
  ControlHandshakeResponse,
  ControlOperationParameter,
  ControlOperationDescriptor,
  ControlOperationCatalog,
  ControlArtifactListResponse,
  ControlProjectOutputsResponse,
  ControlApplyCheckResponse,
  ControlDeliveryResponse,
  ControlJournalInspection,
  ControlJournalValidation,
  ControlJournalExportReceipt,
  ControlJournalQuarantineRequest,
  ControlJournalQuarantineReceipt,
  ControlJournalEvent,
  ThreadHeadPing,
  JournaledRunCreatedPayload,
  Project,
  ControlProject,
  ControlProjectListResponse,
  ControlProjectRegisterRequest,
  ControlProjectRelinkRequest,
  ControlProjectRemoveReceipt,
  ControlDirectoryEntry,
  ControlDirectoryListing,
} as const;

/**
 * zod-to-json-schema silently renders an EMPTY definition (no error) when the
 * input is not a zod/v3 schema instance (e.g. a schema built from bare zod@4).
 * Guard: every registered schema must render SOMETHING. A bare `{}` definition
 * is the exact signature of that silent failure, and no schema in this registry
 * legitimately renders empty — unions and effects included.
 */
function assertRenderedNotSilentlyEmpty(name: string, json: Record<string, unknown>): void {
  const definitions = json.definitions as Record<string, unknown> | undefined;
  const rendered = (definitions?.[name] ?? json) as Record<string, unknown>;
  if (Object.keys(rendered).length > 0) return;
  throw new Error(
    `gen-jsonschema: schema "${name}" rendered an empty definition — ` +
      `zod-to-json-schema was likely handed a non-zod/v3 schema instance.`,
  );
}

for (const [name, schema] of Object.entries(schemas)) {
  // Draft-07 is the newest dialect zod-to-json-schema 3.x actually supports;
  // the previously requested "jsonSchema2020-12" was silently ignored and
  // produced an invalid draft-4/7 hybrid (boolean exclusiveMinimum).
  // CI compiles every generated file with ajv (validate-generated-schemas.mjs).
  const json = zodToJsonSchema(schema, { name, target: "jsonSchema7" }) as Record<string, unknown>;
  assertRenderedNotSilentlyEmpty(name, json);
  json.$schema = "http://json-schema.org/draft-07/schema#";
  writeFileSync(join(outDir, `${name}.schema.json`), JSON.stringify(json, null, 2) + "\n");
}

console.log(`Wrote ${Object.keys(schemas).length} JSON schemas to ${outDir}`);
